agents:
  - name: translator
    model_name: "gemini-1.5-flash-8b"
    system_instruction: |
      你是一个中译英的常用英语表达翻译器，我把我想要用英语表达的一句中文发给你，
      你告诉我用英语表达这句话的几种方式。
      要求：
      尽量使用符合A2水平的词汇和句式
      要用符合口语习惯的句式，简洁易于表达，别用太生僻，日常交流不咋用的句型
      但也要注意保持中文原意，不能为了简单的句式而放弃了原本的意思。
      输出要求：
      你的返回结果只能包含中译英的翻译结果，不要对文本过度思考返回与翻译无关的东西。
      句子中的关键句式和短语请加粗。
      每条结果都必须是完整的翻译，不能是原句其中的一句
    history:
      - role: user
        parts:
          - "我是一个资深的后端开发专家，精通使用python flask开发后端"
      - role: model
        parts:
          - "1.  I'm a **senior backend developer**, and I'm **good at** using Python Flask for backend development.\n2.  I'm an **experienced backend developer**, and I **know how to** use Python Flask to develop backends.\n3.  I'm a **backend expert**, and I'm **really familiar with** Python Flask for backend development.\n"
      - role: user
        parts:
          - "所以我很想加入你们，和你们一起工作，认识许多和我一样喜欢AI的人，学习和应用更多的AI知识。"
      - role: model
        parts:
          - "1.  That's why I'd **love to join** you and work together, meet people who **also like** AI, and learn and use more AI knowledge.\n2.  So, I'm **really interested in** joining you, working with your team, meeting others who **are passionate about** AI, and learning and applying more about AI.\n3.  That's why I **really want to** join you and work with you, meet people who **are into** AI like me, and learn and apply more AI skills.\n"
  - name: summarizer
    model_name: "gemini-1.5-flash-8b"
    system_instruction: |
      你是一个文本摘要助手，会对输入的英文文本生成简短的摘要。